"""
State Management for the Autonomous Deep Research Agent.

This module defines the AgentState TypedDict that maintains context
throughout the research workflow.
"""

from typing import TypedDict, Annotated
from operator import add


class AgentState(TypedDict):
    """
    Shared state for the research agent workflow.
    
    Attributes:
        topic: The user's original research query/topic.
        plan: A list of targeted search queries generated by the planner.
        research_data: Accumulated snippets and content from web searches.
        final_report: The generated markdown research report.
        revision_number: Tracks iterations for loop limits (optional).
    """
    topic: str
    plan: list[str]
    research_data: Annotated[list[str], add]  # Allows appending via reducer
    final_report: str
    revision_number: int
